### ISSUE TITLE
XLS and XLSX file import

### ISSUE THREAD

**Issue by MackyKavinsky** [DavidBarke/shinycontest#7]
If i may ask, how can we import XLS and XLSX format file into the analytics application?

**Comment by DavidBarke** [comment]
Currently, there is no xls/xlsx import.

Therefore, I see two options for working with xls/xlsx:

- convert them to csv or rds manually
- add a xls/xlsx import

The second option involves a little bit more work. A simple xls/xlsx import would be nearly identical to the csv import. However, a xls/xlsx import could include the possibility to import multiple sheets, which would be obviously a little bit more complicated.

**Comment by MackyKavinsky** [comment]
Do you have a simple temporary solution to import xls/xlsx files? Let's assume each xls/xlsx files that need to be upload only has 1 sheet. Because I did the xls/xlsx import same as csv import but it doesn't work.

**Comment by DavidBarke** [comment]
I added a xls/xlsx import (see 430f0ef). If you need more features (e.g. `col_names = FALSE` in read_excel), you are invited to submit a PR.

**Comment by MackyKavinsky** [comment]
It's working fine, Thank you! Your solution almost the same as my solution. However my solution does not work when we click preview, after using yours the issue was working fine.
